# Docker Compose file to launch the development services

version: '3.7'

services:
  api:
    build: ./api
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      # This will be replaced with a per-customer key in the VM on first run
      RAILS_MASTER_KEY: b930614dc507c69da86036078ea460ef
    command: bin/entrypoint rails server

  db:
    image: postgres:10
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mem-store:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  pg-data:
